### ISSUE TITLE
Can not see update on site after I followed each step.

### ISSUE THREAD

**Issue by yy2540** [aws-samples/aws-serverless-workshop-innovator-island#65] opened 2021-09-14 20:30 UTC
**Describe the bug**
The browser caches the older version of the site even I perform a hard fresh on Chrome.

**Link to workshop URL**
https://pages.awscloud.com/AWS-Learning-Path-Build-a-Serverless-Web-App-for-a-Theme-Park_2020_LP_0005-SRV.html
https://www.eventbox.dev/published/lesson/innovator-island/1-deploy/4-update.html

**To Reproduce**
1. Go to 'AWS Amplify Console'
2. Click on the URL of theme-park-frontend
3. See error: My site does not change even I followed each step.
4. On the console, see issue 'Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform'

**Expected behavior**
A step-by-step instruction to fix this issue.

**Screenshots**
![截屏2021-09-14 下午4 25 54](https://user-images.githubusercontent.com/81672984/133329152-d36a9844-e4d1-4765-827a-ead80854b7f5.png)

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - Version [92.0.4515.159]

**Additional context**

**Comment by jbesw** [comment] 2021-09-21 15:26
This issue hints that the problem is the Git repo not being updated. Double-check the results of the git push instruction - this will throw an error if git has not been configured correctly. If you see an error, follow the setup steps in the workshop for correctly configuring git credentials.

Please paste your terminal output if you continue to have issues and I can troubleshoot further.

**Comment by jbesw** [comment] 2021-09-29 12:27
If you continue to have issues, please let me know but I'll close this ticket for now.

**Closed by jbesw** 2021-09-29 12:27 UTC
